/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function MyComponent(props) {
  return (
    <div className="bg-white flex w-[390px] flex-col">
      <div className="justify-center items-center bg-black self-stretch flex w-full flex-col px-16 py-2.5 max-md:px-5">
        <div className="items-start self-stretch flex justify-between gap-2">
          <div className="text-white text-center text-sm font-bold">
            <span className="">Sign up to our </span>
            <span className="font-bold">Slack community</span>
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/db764e23-1ead-43f4-87ce-3d7a11494c75?apiKey=b7584ebc3b16452c99f7efe3359b51e6&"
            className="aspect-square object-contain object-center w-5 overflow-hidden max-w-full self-start"
          />
        </div>
      </div>
      <div className="items-center bg-red-800 self-stretch flex w-full flex-col pl-20 pr-20 pt-10 pb-8 max-md:px-5">
        <div className="text-white text-center text-4xl font-black self-center whitespace-nowrap">
          ByteMe
        </div>
        <div className="text-white text-center text-base leading-6 self-stretch mt-5">
          <span className="font-bold">3rd - 5th May, 2024</span>
          <span className=""> This is by no means a hackathon</span>
        </div>
        <div className="justify-center items-center content-center flex-wrap self-center flex w-[184px] max-w-full flex-col mt-6">
          <div className="text-white text-center text-sm underline self-stretch">
            Structure and sessions
          </div>
          <div className="self-center flex w-[130px] max-w-full items-start gap-4 mt-3">
            <div className="text-white text-center text-sm underline self-stretch">
              Prizes
            </div>
            <div className="text-white text-center text-sm underline self-stretch whitespace-nowrap">
              Sponsors
            </div>
          </div>
        </div>
      </div>
      <div className="text-neutral-700 text-center text-xl font-bold self-center max-w-[249px] mt-11 max-md:mt-10">
        Sign up now
      </div>
      <div className="items-start self-center flex w-[326px] max-w-full flex-col mt-4">
        <div className="items-start self-stretch flex flex-col px-5">
          <div className="items-start self-stretch flex flex-col -mr-5">
            <div className="text-neutral-700 text-base leading-6 self-stretch whitespace-nowrap">
              First name
            </div>
            <div className="self-stretch flex grow flex-col mt-2">
              <div className="text-zinc-500 text-sm leading-5 self-stretch whitespace-nowrap rounded border border-[color:var(--grey-grey-40,#CCC)] bg-white w-full grow pl-4 pr-20 py-3.5 border-solid max-md:pr-5">
                First name
              </div>
            </div>
          </div>
          <div className="items-start self-stretch flex flex-col -mr-5 mt-6">
            <div className="text-neutral-700 text-base leading-6 self-stretch whitespace-nowrap">
              Last name
            </div>
            <div className="self-stretch flex grow flex-col mt-2">
              <div className="text-zinc-500 text-sm leading-5 self-stretch whitespace-nowrap rounded border border-[color:var(--grey-grey-40,#CCC)] bg-white w-full grow pl-4 pr-20 py-3.5 border-solid max-md:pr-5">
                Last name
              </div>
            </div>
          </div>
          <div className="items-start self-stretch flex flex-col -mr-5 mt-6">
            <div className="text-neutral-700 text-base leading-6 self-stretch whitespace-nowrap">
              Tell us about yourself in one sentence
            </div>
            <div className="self-stretch flex grow flex-col mt-2">
              <div className="text-zinc-500 text-sm leading-5 self-stretch whitespace-nowrap rounded border border-[color:var(--grey-grey-40,#CCC)] bg-white w-full grow pl-4 pr-20 pt-3.5 pb-9 border-solid max-md:pr-5">
                A one-liner about you
              </div>
            </div>
          </div>
          <div className="text-neutral-700 text-base leading-6 self-stretch whitespace-nowrap -mr-5 mt-6">
            Choose your player
          </div>
          <div className="self-stretch flex items-start justify-between gap-3.5 -mr-5 mt-3">
            <div className="self-stretch flex flex-col w-[99px]">
              <div className="text-red-700 text-center text-base font-semibold leading-6 self-stretch whitespace-nowrap justify-center items-center rounded border bg-white w-full px-5 py-3 border-solid border-stone-300 max-md:px-5">
                Hipster
              </div>
              <div className="text-neutral-700 text-center text-xs underline mt-3">
                Learn more
              </div>
            </div>
            <div className="self-stretch flex flex-col">
              <div className="self-stretch flex items-start justify-between gap-3.5">
                <div className="text-red-700 text-center text-base font-semibold leading-6 self-stretch whitespace-nowrap justify-center items-center rounded border bg-white flex-1 pl-6 pr-6 py-3 border-solid border-stone-300 max-md:px-5">
                  Hacker
                </div>
                <div className="text-red-700 text-center text-base font-semibold leading-6 self-stretch whitespace-nowrap justify-center items-center rounded border bg-white flex-1 px-5 py-3 border-solid border-stone-300 max-md:px-5">
                  Hustler
                </div>
              </div>
              <div className="self-center flex w-[179px] max-w-full items-start justify-between gap-5 mt-3">
                <div className="text-neutral-700 text-center text-xs underline self-stretch">
                  Learn more
                </div>
                <div className="text-neutral-700 text-center text-xs underline self-stretch">
                  Learn more
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="justify-between items-start self-stretch flex gap-3 mt-8 px-5">
          <div className="rounded border border-[color:var(--grey-grey-70-subdued,#7F7F7F)] bg-white self-stretch flex w-6 h-6 flex-col grow shrink-0 basis-auto border-solid" />
          <div className="justify-center text-neutral-700 text-sm leading-5 self-center grow shrink basis-auto my-auto">
            I have a group already
          </div>
        </div>
      </div>
      <div className="justify-center items-center bg-white self-stretch flex w-full flex-col mt-6 mb-24 pt-6 pb-12 px-20 max-md:mb-10 max-md:px-5">
        <div className="justify-center items-center rounded bg-neutral-200 self-stretch flex w-full flex-col px-20 py-3 max-md:px-5">
          <div className="text-zinc-500 text-center text-base font-semibold leading-6 self-center whitespace-nowrap">
            Submit
          </div>
        </div>
      </div>
    </div>
  );
}